### ISSUE TITLE
Set a new name for the project

### ISSUE THREAD

**Issue by maehler** [genomic-medicine-sweden/Twist_DNA_Hematology#37]
Suggestions:

- Twist_Hematology
- Twist_Myeloid (if the lymphoid panel will run on something else)
- Brongersmai (*Python brongersmai* is a species of snake with the common name Blood Python)
- gawa (initials of Gabriel Andral and Willam Addison, the first people to describe leukocytes)
- Poppy (Madame Pomfrey's first name)

**Comment by elleira** [comment]
Might be a liiittle biased since my dog is called Poppy :dog: so i vote for Poppy!   Or Brogersmai :snake: (just have to figure out how to pronounce it)

**Comment by maehler** [comment]
> just have to figure out how to pronounce it

In my opinion, this would disqualify it immediately.

I like Poppy; short and easy to pronounce. Probably also backronym friendly if we want to go that route (please don't). Being sick and not able to do anything that requires brain capacity, I sketched up a logo that might fit:

<img width="240" alt="poppy" src="https://github.com/genomic-medicine-sweden/Twist_DNA_Hematology/assets/2573608/e67326b8-4e20-40dc-a992-0fd76d91abf9">

**Comment by alvaralmstedt** [comment]
Yeah go for Poppy. Sounds nice and snappy 👍

**Comment by maehler** [comment]
The consensus from today's meeting is that we go for Poppy. There is however an ongoing discussion about standardizing the naming of pipelines within GMS, so before I start updating the repo settings I will wait and see what will come from these discussions.

**Comment by elleira** [comment]
But add the logo to the repo! :snake: :woman_health_worker:

**Comment by maehler** [comment]
> But add the logo to the repo! 🐍 👩‍⚕️

Will do! I can update the README for now.
