### ISSUE TITLE
Make dev branch default?

### ISSUE THREAD

**Issue by maehler** [genomic-medicine-sweden/Twist_DNA_Hematology#6]
Pros:

- Can close issues from commit messages and pull requests
- Pull requests are made against dev by default
- Should probably be the branch that is seen when landing on [genomic-medicine-sweden/Twist_DNA_Hematology](https://github.com/genomic-medicine-sweden/Twist_DNA_Hematology)

**Comment by elleira** [comment]
Yeah that sounds good!

**Comment by maehler** [comment]
Done!
